### ISSUE TITLE
Disk discovery is only possible after applying the cluster.yaml file.

### ISSUE THREAD

**Issue by sp98** [alauda/topolvm-operator#18]
```
Use case:  As a storage admin, I should be able to discover available disks on the cluster in order to make better decisions while creating LVM volume groups. 
```

TopoLVM operator has a discovery mechanism that stores the discovered device results in the `lvmdconfig-<nodeName>` config map under `data.devices`  This works well, but the config map is available only after the cluster CR is applied.  So list of available disks is not available to the user (Storage Admin) before creating the cluster. 

@fanzy618  @little-guy-lxr  This is not an issue but just a use case for device discovery. Is there a way to get list of devices before cluster CR is applied?  What do you guys think about this use case?

Also, is there a more convenient way to reach out to you guys for questions? (slack, etc)

Thanks.

**Comment by little-guy-lxr** [comment]
> ```
> Use case:  As a storage admin, I should be able to discover available disks on the cluster in order to make better decisions while creating LVM volume groups. 
> ```
> 
> TopoLVM operator has a discovery mechanism that stores the discovered device results in the `lvmdconfig-<nodeName>` config map under `data.devices` This works well, but the config map is available only after the cluster CR is applied. So list of available disks is not available to the user (Storage Admin) before creating the cluster.
> 
> @fanzy618 @little-guy-lxr This is not an issue but just a use case for device discovery. Is there a way to get list of devices before cluster CR is applied? What do you guys think about this use case?
> 
> Also, is there a more convenient way to reach out to you guys for questions? (slack, etc)
> 
> Thanks.

Your suggestion is very good.  We used discovery mechanism to discover new added devices when node has new available devices. and we didn't export  devices to user Storage Admin who could view and choose device to add to topolvm cluster. Next step, we will considerate youre suggestion.

you could communicate with us by xrluo@alauda.io

**Comment by sp98** [comment]
> you could communicate with us by [xrluo@alauda.io](mailto:xrluo@alauda.io)

@little-guy-lxr  Communicating over email might not be very convenient. Are you on the Topolvm slack channel ?  (topolvm.slack.com) If not, then would you like to join this channel so that we can communicate over there?

**Comment by little-guy-lxr** [comment]
> > you could communicate with us by [xrluo@alauda.io](mailto:xrluo@alauda.io)
> 
> @little-guy-lxr Communicating over email might not be very convenient. Are you on the Topolvm slack channel ? (topolvm.slack.com) If not, then would you like to join this channel so that we can communicate more over there?

yes , i am on the topolvm slack channel, my account is xiaoren luo.
