### ISSUE TITLE
Topolvm operator uses forked version of topolvm

### ISSUE THREAD

**Issue by sp98** [alauda/topolvm-operator#23]
@little-guy-lxr 

Our team at Red Hat is willing to contribute to Topolvm operator.

Currently Topolvm Operator uses a forked version of Topolvm. However, we would prefer to use the main topolvm project instead of a forked version

The operator doc suggests two major changes in the forked version:
a) remove topolvm-scheduler
b) lvmd containerized

- TopoLVM project now provides a way to run lvmd as a container. See [](https://github.com/topolvm/topolvm/blob/main/deploy/README.md#setup-lvmd-using-kubernetes-daemonset)

 Do you think Topolvm operator could start using the original project instead of the forked version ?

**Comment by little-guy-lxr** [comment]
> @little-guy-lxr
> 
> Our team at Red Hat is willing to contribute to Topolvm operator.
> 
> Currently Topolvm Operator uses a forked version of Topolvm. However, we would prefer to use the main topolvm project instead of a forked version
> 
> The operator doc suggests two major changes in the forked version: a) remove topolvm-scheduler b) lvmd containerized
> 
> * TopoLVM project now provides a way to run lvmd as a container. See
> 
> Do you think Topolvm operator could start using the original project instead of the forked version ?

@sp98 thanks for your greate suggestion and reat hat team's willingness to contribute.
if we use the original project , user must start lvmd service in each node and config extension scheduler in api-server that  is troublesome and fallible. but if you have a better solution, we welcome it, we could support both origin project and forked version. 

Looking forward to your good ideas.

**Comment by jmolmo** [comment]
@little-guy-lxr: last modifications has been done in "branch" main,  but we already have the origin-topolvm branch. It seems sensible to use only one "main" branch, as for our understanding, the one using the main topolvm project is the right one.

For the moment, we can move changes between branches but probably that is not something sustainable.
Do we need something additional in the branch "origin-topolvm-image"? How can we start to use only ""origin-topolvm-image" as "main" branch?

**Comment by little-guy-lxr** [comment]
done !
