### ISSUE TITLE
Failed to create (intermittent) prepareVG job on AWS

### ISSUE THREAD

**Issue by leelavg** [alauda/topolvm-operator#65]
- Did the usual, created a OCP cluster, added disks, installed operator etc
- Operator Image (created from `origin-topolvm` branch): `quay.io/rhn_support_lgangava/toperator:origin`

- Issue:
1. Unable to deploy pod for preparing volume group
```
# k describe jobs topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal                                                                                                             
Name:             topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal                                                                                                             
Namespace:        topolvm-system  
[...]
Events:
  Type     Reason        Age   From            Message
  ----     ------        ----  ----            -------
Warning  FailedCreate  30s   job-controller  Error creating: Pod "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-wxw6f" is invalid: [metadata.generateName: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-wxw6f": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
[...]
```
- Corresponding code lgtm but not sure why the pod name is starting with double hyphens `--1-` 🤔 
https://github.com/alauda/topolvm-operator/blob/dad1c0a07d8bbe436c79301208d15b0e1806754f/pkg/operator/volumegroup/vgmanager.go#L144-L151

**Comment by little-guy-lxr** [comment]
> * Did the usual, created a OCP cluster, added disks, installed operator etc
> * Operator Image (created from `origin-topolvm` branch): `quay.io/rhn_support_lgangava/toperator:origin`
> * Issue:
> 
> 1. Unable to deploy pod for preparing volume group
> 
> ```
> # k describe jobs topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal                                                                                                             
> Name:             topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal                                                                                                             
> Namespace:        topolvm-system  
> [...]
> Events:
>   Type     Reason        Age   From            Message
>   ----     ------        ----  ----            -------
> Warning  FailedCreate  30s   job-controller  Error creating: Pod "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-wxw6f" is invalid: [metadata.generateName: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-wxw6f": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
> [...]
> ```
> 
> * Corresponding code lgtm but not sure why the pod name is starting with double hyphens `--1-` 🤔
>   https://github.com/alauda/topolvm-operator/blob/dad1c0a07d8bbe436c79301208d15b0e1806754f/pkg/operator/volumegroup/vgmanager.go#L144-L151
@leelavg is problem always come up ?  please provide kubernetes version.

**Comment by leelavg** [comment]
- Issue is reproducible with `alaudapublic/topolvm-operator:2.2.0` as well, just tested the same
- Yep, it's reproducible every-time in the cluster created today
```
-> oc version
Client Version: 4.9.0
Server Version: 4.9.5
Kubernetes Version: v1.22.0-rc.0+a44d0f0

-> oc get node
NAME                                          STATUS   ROLES           AGE     VERSION
ip-10-0-155-231.ap-south-1.compute.internal   Ready    master,worker   3h43m   v1.22.0-rc.0+a44d0f0
```
- It was working with below node name (previous week, I can see one extra digit in the cluster created today `231` vs `84`)
```
-> oc get no                                                                                                                                                                                   
NAME                                         STATUS   ROLES           AGE   VERSION           
ip-10-0-140-84.ap-south-1.compute.internal   Ready    master,worker   47m   v1.22.0-rc.0+894a78b  
```

**Comment by little-guy-lxr** [comment]
@leelavg  can you provide the yaml of the job?

**Comment by leelavg** [comment]
- here you go, providing CR as well if that helps in any way
``` yaml
---
apiVersion: topolvm.cybozu.com/v2
kind: TopolvmCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"topolvm.cybozu.com/v2","kind":"TopolvmCluster","metadata":{"annotations":{},"name":"sample-cr","namespace":"topolvm-system"},"spec":{"storage":{"deviceClasses":[{"classes":[{"className":"hdd","default":true,"devices":[{"name":"/dev/nvme1n1","type":"disk"},{"name":"/dev/nvme2n1","type":"disk"}],"volumeGroup":"test-master-0"},{"className":"ssd","devices":[{"name":"/dev/nvme3n1","type":"disk"}],"volumeGroup":"test-master-1"}],"nodeName":"ip-10-0-155-231.ap-south-1.compute.internal"}],"useAllDevices":false,"useAllNodes":false,"useLoop":false},"topolvmVersion":"quay.io/topolvm/topolvm-with-sidecar:0.10.2"}}
  creationTimestamp: "2021-11-15T08:56:19Z"
  finalizers:
  - topolvmcluster.topolvm.cybozu.com
  generation: 2
  name: sample-cr
  namespace: topolvm-system
  resourceVersion: "80534"
  uid: e2e4a6ff-a78c-4b66-af18-049cb1acfbf2
spec:
  storage:
    deviceClasses:
    - classes:
      - className: hdd
        default: true
        devices:
        - name: /dev/nvme1n1
          type: disk
        - name: /dev/nvme2n1
          type: disk
        volumeGroup: test-master-0
      - className: ssd
        default: false
        devices:
        - name: /dev/nvme3n1
          type: disk
        volumeGroup: test-master-1
      nodeName: ip-10-0-155-231.ap-south-1.compute.internal
    useAllDevices: false
    useAllNodes: false
    useLoop: false
  topolvmVersion: quay.io/topolvm/topolvm-with-sidecar:0.10.2
status:
  nodeStorageState:
  - failClasses: null
    loops: null
    node: ip-10-0-155-231.ap-south-1.compute.internal
    phase: Failure
    successClasses: null
  phase: Failure
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-11-15T08:56:41Z"
  generation: 1
  labels:
    app.kubernetes.io/name: prepareVolumeGroup
    topolvm_cluster: topolvm-system
  name: topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal
  namespace: topolvm-system
  ownerReferences:
  - apiVersion: topolvm.cybozu.com/v2
    blockOwnerDeletion: true
    controller: true
    kind: TopolvmCluster
    name: sample-cr
    uid: e2e4a6ff-a78c-4b66-af18-049cb1acfbf2
  resourceVersion: "80620"
  uid: 91233e09-1333-4212-b1ba-4051ff059e6e
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 91233e09-1333-4212-b1ba-4051ff059e6e
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: prepareVolumeGroup
        controller-uid: 91233e09-1333-4212-b1ba-4051ff059e6e
        job-name: topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal
        topolvm_cluster: topolvm-system
      name: prepareVolumeGroup
    spec:
      containers:
      - command:
        - /topolvm
        - prepareVg
        env:
        - name: NODE_NAME
          value: ip-10-0-155-231.ap-south-1.compute.internal
        - name: POD_NAMESPACE
          value: topolvm-system
        - name: TOPOLVM_LOG_LEVEL
          value: DEBUG
        - name: CLUSTER_NAME
          value: sample-cr
        image: quay.io/rhn_support_lgangava/toperator:origin
        imagePullPolicy: IfNotPresent
        name: preparevg
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev
          name: devices
        - mountPath: /run/udev
          name: udev
      dnsPolicy: ClusterFirst
      hostIPC: true
      hostPID: true
      nodeName: ip-10-0-155-231.ap-south-1.compute.internal
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-155-231.ap-south-1.compute.internal
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: topolvm-preparevg
      serviceAccountName: topolvm-preparevg
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /dev
          type: ""
        name: devices
      - hostPath:
          path: /run/udev
          type: ""
        name: udev
status: {}
---
```

**Comment by little-guy-lxr** [comment]
> ```yaml
> dev
> ```

@leelavg  see https://github.com/kubernetes/kubernetes/pull/105676 . your kubernetes my not fix that.

**Comment by leelavg** [comment]
- thanks for the link however that does seems a little bit complex
- does setting `completionMode` as `NonIndexed` if k8s api <1.21 and set as `Indexed` otherwise would be a good workaround?
- one small request, if possible can you pls write a line or two about the commits, I thought #68 fixes this issue 😅

**Comment by little-guy-lxr** [comment]
> * thanks for the link however that does seems a little bit complex to workaround
> * does setting `completionMode` as `NonIndexed` if k8s api <1.21 and set as `Indexed` otherwise would be a good workaround?
> * one small request, if possible can you pls write a line or two about the commits, I thought [fix prepare job pod template #68](https://github.com/alauda/topolvm-operator/pull/68) fixes this issue 😅
 @leelavg #68  not fixes this issue, so i don't add fix info to commits. I think the index job issue is for k8s >= 1.22. the job `completionMode` default is `NonIndexed`, so if k8s version is <=1.21 , there is no problem.

**Comment by leelavg** [comment]
- Thanks for the clarification
- Yes, for version <=1.21 there'll be no issue, however users will definitely be upgrading, so IMHO this is worth fixing, what's your opinion?

**Comment by little-guy-lxr** [comment]
> * Thanks for the clarification
> * Yes, for version <=1.21 there'll be no issue, however users will definitely be upgrading, so IMHO this is worth fixing, what's your opinion?

@leelavg  I agree with you， i think we could set job `completionMode` to `Indexed` as workaround for k8s 1.22

**Comment by leelavg** [comment]
- my bad, I didn't see that you have assigned it to yourself and almost completed the PR
- from next time, if I'm picking up an issue will assign it to my name and thanks for the fix, mine was also along the similar lines 😄

**Comment by little-guy-lxr** [comment]
@leelavg  could you help me debug why always report that the go mod is incorrect. I run make test locally all passed, i guess  maybe I use goproxy that cause package out of sync.  thank you.

```
Run make test
go fmt ./...
go vet ./...
/home/runner/work/topolvm-operator/topolvm-operator/bin/staticcheck ./...
/home/runner/work/topolvm-operator/topolvm-operator/bin/ineffassign ./...
sudo go test -race -v $(go list ./... | grep -v vendor | grep -v e2e)
go: github.com/rook/rook@v1.7.5 requires
	github.com/libopenstorage/secrets@v0.0.0-20210709082113-dde442ea20ec requires
	github.com/portworx/sched-ops@v0.0.0-20200831185134-3e8010dc7056: github.com/portworx/sched-ops(v0.0.0-20200831185134-3e8010dc7056) depends on excluded k8s.io/client-go(v12.0.0+incompatible) with no newer version available
make: *** [Makefile:20: test] Error 1
Error: Process completed with exit code 2.


```
